'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import Image from 'next/image';
import { asset } from '@/lib/asset';

interface Ingredient {
  id: number;
  name: string;
  description: string;
  src: string;
}

const ingredients: Ingredient[] = [
  {
    id: 1,
    name: 'Ectoin',
    description:
      'Helps protect skin from environmental stress caused by heat, UV and pollution',
    src: '/skinwear-media/model-portrait.jpg',
  },
  {
    id: 2,
    name: 'Beta Glucan',
    description:
      'Supports the skin barrier against daily environmental stress while helping maintain comfort',
    src: '/skinwear-media/model-portrait.jpg',
  },
  {
    id: 3,
    name: 'Camellia Sinensis Leaf Extract',
    description:
      'Helps neutralise free radicals generated by UV exposure and pollution.',
    src: '/skinwear-media/model-portrait.jpg',
  },
  {
    id: 4,
    name: 'Bisabolol',
    description:
      'Helps reduce visible signs of irritation caused by environmental exposure.',
    src: '/skinwear-media/model-portrait.jpg',
  },
  {
    id: 5,
    name: 'Sodium Hyaluronate',
    description:
      'Helps retain moisture as humidity and environmental conditions change.',
    src: '/skinwear-media/model-portrait.jpg',
  },
  {
    id: 6,
    name: 'Betaine',
    description:
      'Supports the skin’s natural moisture balance across changing climates.',
    src: '/skinwear-media/model-portrait.jpg',
  },
];

const marqueeList = [...ingredients, ...ingredients];

export default function ClimateRoutineGallery() {
  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);

  return (
    <section className="relative z-10 w-full min-h-[85vh] flex flex-col items-center justify-center py-16 text-[var(--brand-cream)] overflow-hidden">

      {/* Heading */}
      <motion.h2
        initial={{ opacity: 0, y: -20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: '-100px' }}
        transition={{ duration: 0.8 }}
        className="text-center font-sans text-xl md:text-2xl font-normal opacity-95 max-w-[1250px] mb-8 leading-relaxed px-4"
      >
        Made to hold through early mornings, back-to-back meetings, the afternoon sun,
        <br className="hidden md:block" />
        the commute home and everything in between.
      </motion.h2>

      {/* Marquee */}
      <div className="w-full relative overflow-hidden py-4 group">
        <div className="marquee-track flex gap-4 md:gap-6 w-max">
          {marqueeList.map((item, index) => {
            const isHovered = hoveredIndex === index;

            return (
              <div
                key={`${item.id}-${index}`}
                onMouseEnter={() => setHoveredIndex(index)}
                onMouseLeave={() => setHoveredIndex(null)}
                className="relative w-[220px] sm:w-[280px] md:w-[320px] h-[300px] sm:h-[380px] md:h-[420px] flex-shrink-0 overflow-hidden cursor-pointer"
              >
                {/* Image */}
                <Image
                  src={asset(item.src)}
                  alt={item.name}
                  fill
                  className={`object-cover transition-all duration-700 ease-out ${isHovered
                    ? 'blur-md scale-110 brightness-[0.4]'
                    : 'blur-0 scale-100 brightness-100'
                    }`}
                />

                {/* Overlay */}
                <div
                  className={`absolute inset-0 transition-all duration-500 ${isHovered
                    ? 'opacity-100 bg-black/30'
                    : 'opacity-0'
                    }`}
                />

                {/* Content */}
                <div
                  className={`absolute inset-0 z-20 flex flex-col items-center justify-center text-center px-6 transition-opacity duration-300 ${isHovered
                      ? 'opacity-100'
                      : 'opacity-0 pointer-events-none'
                    }`}
                >
                  <h3 className="font-editorial text-2xl sm:text-3xl md:text-4xl font-normal mb-4 tracking-wide text-[var(--brand-cream)]">
                    {item.name}
                  </h3>

                  <p className="font-sans text-xs sm:text-sm md:text-base font-light leading-relaxed max-w-[260px] text-[var(--brand-cream)]">
                    {item.description}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      <style jsx>{`
  .marquee-track {
    animation: marquee-scroll 60s linear infinite;
  }

  .marquee-track:hover {
    animation-play-state: paused;
  }

  @keyframes marquee-scroll {
    from {
      transform: translateX(0);
    }

    to {
      transform: translateX(-50%);
    }
  }
`}</style>

    </section>
  );
}