'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import Image from 'next/image';
import { asset } from '@/lib/asset';

interface Ingredient {
  id: number;
  name: string;
  description: string;
  src: string;
}

const ingredients: Ingredient[] = [
  {
    id: 1,
    name: 'Ectoin',
    description: 'Helps protect skin from environmental stress caused by heat, UV and pollution',
    src: '/skinwear-media/model-portrait.jpg',
  },
  {
    id: 2,
    name: 'Beta Glucan',
    description: 'Supports the skin barrier against daily environmental stress while helping maintain comfort',
    src: '/skinwear-media/model-portrait.jpg',
  },
  {
    id: 3,
    name: 'Camellia Sinensis Leaf Extract',
    description: 'Helps neutralise free radicals generated by UV exposure and pollution.',
    src: '/skinwear-media/model-portrait.jpg',
  },
  {
    id: 4,
    name: 'Bisabolol',
    description: 'Helps reduce visible signs of irritation caused by environmental exposure.',
    src: '/skinwear-media/model-portrait.jpg',
  },
  {
    id: 5,
    name: 'Sodium Hyaluronate',
    description: 'Helps retain moisture as humidity and environmental conditions change.',
    src: '/skinwear-media/model-portrait.jpg',
  },
  {
    id: 6,
    name: 'Betaine',
    description: 'Supports the skin’s natural moisture balance across changing climates.',
    src: '/skinwear-media/model-portrait.jpg',
  },
];

// Infinite Marquee duplicate
const marqueeList = [...ingredients, ...ingredients];

export default function ClimateRoutineGallery() {
  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);

  return (
    <section className="relative z-10 w-full min-h-[85vh] flex flex-col items-center justify-center py-16 text-[var(--brand-cream)] overflow-hidden">
      
      {/* 1. Headline */}
      <motion.h2
        initial={{ opacity: 0, y: -20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: '-100px' }}
        transition={{ duration: 0.8 }}
        className="text-center font-sans text-xl md:text-2xl font-normal opacity-95 max-w-[1250px] mb-8 leading-relaxed px-4"
      >
        Made to hold through early mornings, back-to-back meetings, the afternoon sun,<br className="hidden md:block" />
        the commute home and everything in between.
      </motion.h2>

      {/* 2. Train Marquee (60s loop) - Hover to Pause & Blur with Info */}
      <div className="w-full relative overflow-hidden py-4">
        <motion.div
          className="flex gap-4 md:gap-6 w-max"
          animate={{ x: ['0%', '-50%'] }}
          transition={{
            repeat: Infinity,
            repeatType: 'loop',
            duration: 60,
            ease: 'linear',
          }}
          style={{
            animationPlayState: hoveredIndex !== null ? 'paused' : 'running',
          }}
        >
          {marqueeList.map((item, index) => {
            const isHovered = hoveredIndex === index;

            return (
              <div
                key={`${item.id}-${index}`}
                onMouseEnter={() => setHoveredIndex(index)}
                onMouseLeave={() => setHoveredIndex(null)}
                className="relative w-[220px] sm:w-[280px] md:w-[320px] h-[300px] sm:h-[380px] md:h-[420px] flex-shrink-0 overflow-hidden rounded-none cursor-pointer bg-black/20"
              >
                {/* Image */}
                <Image
                  src={asset(item.src)}
                  alt={item.name}
                  fill
                  className={`object-cover transition-all duration-500 ${
                    isHovered ? 'filter blur-md scale-105' : 'scale-100'
                  }`}
                />

                {/* Dark Overlay when hovered for text readability */}
                <div
                  className={`absolute inset-0 bg-black/50 transition-opacity duration-300 ${
                    isHovered ? 'opacity-100' : 'opacity-0'
                  }`}
                />

                {/* Name and Feature Text on Hover */}
                <div
                  className={`absolute inset-0 z-10 flex flex-col items-center justify-center text-center p-6 transition-opacity duration-300 ${
                    isHovered ? 'opacity-100' : 'opacity-0 pointer-events-none'
                  }`}
                >
                  <h3 className="font-editorial text-2xl sm:text-3xl md:text-4xl font-normal mb-3 tracking-wide text-[var(--brand-cream)]">
                    {item.name}
                  </h3>
                  <p className="font-sans text-xs sm:text-sm md:text-base font-light opacity-95 leading-relaxed">
                    {item.description}
                  </p>
                </div>
              </div>
            );
          })}
        </motion.div>
      </div>

    </section>
  );
}